### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Shekharrajak**
Enjoy!

### CODE REVIEW

**Comment by rgommers** [comment]
@Shekharrajak browsing the diff, something is still wrong. There's `de/en/`, `hi/`, `hi/en/` and so on. I'd suggest to make sure German and Hindi are gone, and that there's only `nl/` and no `nl/en/`

**Comment by Shekharrajak** [comment]
@rgommers Yeah! I am discussing the same with crowdin team in slack. I have already [changed the source folder as `content/en/*md`](https://github.com/numpy/numpy.org/blob/master/crowdin.yml#L6) but it took the other folders `content/nl` , `content/hi` as well.

**Comment by Shekharrajak** [comment]
I just now did new translation using crowdin translator and new auto PR is : https://github.com/numpy/numpy.org/pull/142

**Comment by Shekharrajak** [comment]
Currently corwdin configuration is : 

```
project_identifier: PROJECT_IDENTIFIER_CROWDIN
api_key: API_KEY_CROWDIN
base_path: ./
preserve_hierarchy: true
files:
  - source: /content/en/*.md
    translation: /content/%two_letters_code%/%original_file_name%

```

Now I will change it to: 

```
project_identifier: PROJECT_IDENTIFIER_CROWDIN
api_key: API_KEY_CROWDIN
base_path: ./
preserve_hierarchy: true
files:
  - source: /content/en/*.md
    translation: /content/%two_letters_code%_%original_file_name%
```

**Comment by rgommers** [comment]
Nice, thanks @Shekharrajak. I'll have a look at the Slack conversation

**Pull request closed without merging**
