### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
This mirrors all the English to English, in the absence of translations. I won't merge it yet. Once people start translating, this PR will be updated with those translations automatically.

**Comment by goanpeca** [comment]
Hi @rgommers, might be useful to use a bot account for doing the Crowdin integration.

Also, something to consider is how to add Crwodin contributors to visible place/file. A bot could also handle this every now and then via de Crowdin API. https://support.crowdin.com/api/v2/#tag/Reports

**Comment by rgommers** [comment]
> Hi @rgommers, might be useful to use a bot account for doing the Crowdin integration.

Good suggestion, thanks @goanpeca. May be a while before I get around to that, but we should do this before merging the first full translation - which I hope and expect will be later this month.

> Also, something to consider is how to add Crwodin contributors to visible place/file. A bot could also handle this every now and then via de Crowdin API. https://support.crowdin.com/api/v2/#tag/Reports

That sounds like a good idea. We still have a `THANKS.txt` file in the main numpy repo, which is a little braindead and we should replace it with a contributors list on a numpy.org page - translators can be added there.

**Comment by goanpeca** [comment]
>May be a while before I get around to that, but we should do this before merging the first full translation - which I hope and expect will be later this month.

No worries :-) 

>That sounds like a good idea. We still have a THANKS.txt file in the main numpy repo, which is a little braindead and we should replace it with a contributors list on a numpy.org page - translators can be added there.

Makes sense, I started playing with Crowdin API but ran into something, I am waiting on their feedback, then I think I can move on with this part.

**Comment by seiko2plus** [comment]
is there any possibility to see the Arabic language? Do we have issues with RTL?

**Comment by rgommers** [comment]
> is there any possibility to see the Arabic language? Do we have issues with RTL?

I'd love to have an Arabic translation. I'm not aware of a particular issue with right-to-left languages, but we also haven't tried. The plan was to get some of the largest languages up first and then expand from there, however I haven't been able to focus on coordinating translations and recruiting many volunteers. Brazilian Portuguese is the farthest along right now. See https://github.com/numpy/numpy/wiki/Translations-of-the-NumPy-website for enabled languages. 

We're using Hugo, and https://discourse.gohugo.io/t/trying-to-include-arabic-in-a-multilingual-website/17739/5 seems to indicate it shouldn't be hard to add Arabic, just needs a tiny bit of CSS (Cc @joelachance in case he knows more about this topic).

If you're interested or know of other people who would like to help, I'd be happy to enable Arabic in the Crowdin interface now @seiko2plus.

**Comment by rgommers** [comment]
This keeps triggering TravisCI, closing. Will see how to regenerate in Crowdin based on latest master.

**Pull request closed without merging**
