### PR TITLE
Add names of "buckets" under Ecosystem on the front page

### PR DESCRIPTION
**Pull request by rgommers**
Wanted to open this for discussion, to see if these are the right headings/buckets to use or if people have better ideas.

Haven't found the time to write this content unfortunately.

### CODE REVIEW

**Comment by rgommers** [comment]
Some good feedback from @mkg33 was to emphasize also individual scientific domains. One way to do that is copy what https://julialang.org/ does: a "Scientific Domains" tab that then just a range of domains with some explanation and links. It manages to list eight distinct science domains in one paragraph.

**Comment by rgommers** [comment]
Okay went with the "Scientific Domains" idea for now. Will merge so we can iterate easier.

**Comment by rgommers** [comment]
We have CI, and it's green:)

@Shekharrajak something didn't quite work, output is:
```
Run echo "The deployed-domain is "
  echo "The deployed-domain is "
  shell: /bin/bash -e {0}
The deployed-domain is 
```
and nothing got deployed. maybe you can look into that?

**Comment by Shekharrajak** [comment]
I am looking at this issue. Thanks for letting me know.

**Comment by Shekharrajak** [comment]
Fixed athttps://github.com/numpy/numpy.org/pull/58

**Pull request merged**
