### PR TITLE
Added presentation templates for NumPy talks

### PR DESCRIPTION
**Pull request by shaloo**
#### Brief description of what is fixed or changed
Two presentation templates for NumPy talks.
Works for both Powerpoint and Google Slides.

#### Deployed URL

http://numpy-<pr_number>.surge.sh/

### CODE REVIEW

**Comment by mattip** [comment]
I am not sure this belongs here since this is the repo for the website. Perhaps https://github.com/numpy/archive/tree/master/presentation-resources?

**Comment by shaloo** [comment]
I was a bit confused.  Earlier, I created this https://github.com/numpy/archive/issues/27 and then based on some discussion we had in oct/Jan about information map thought of storing the branding stuff here.  I am okay to put it in NumPy/archive but don't have permission to do the same.

**Comment by rgommers** [comment]
Hi Shaloo, you have permissions now. I reopened https://github.com/numpy/archive/issues/27 and assigned it to you. Can you please resubmit there?

I'll close this.

**Comment by shaloo** [comment]
thanks, will create a fork and then issue a PR

**Pull request closed without merging**
