### PR TITLE
Specify RGB values in the docs regarding the NumPy website color palette

### PR DESCRIPTION
**Pull request by aerikpawson**
Specifying RGB values in the docs regarding the NumPy website color palette. Partially fixes #numpygh-398 numpy/numpy.org#398.

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
Thanks for tackling this issue @aerikpawson!

The added RGB values all look good. It would be nice to keep the color names I think. Is there a reason why you removed them?

**Comment by aerikpawson** [comment]
@rgommers  The names of the colors were removed not to mislead users since these names can change. For example, the color with the RGB value of 1/50/67, originally known as “Warm Black”,  is now called “Gunmetal”; the color with the RGB value of 238/238/238, formerly known as “Isabelline”,  can be found named as “Cultured” or “Whisper” depending on what sources you use.

**Comment by rgommers** [comment]
Ah okay, fair enough - thanks for the explanation. Merging then. Thanks again @aerikpawson

**Comment by aerikpawson** [comment]
Cool. Thank you, @rgommers!

**Pull request merged**
