### PR TITLE
Feature/86 cleaner style for Ecosystem tabs widget

### LINKED ISSUE #86: Update tab styling for mobile
The homepage tabs need to be updated for mobile. Improve the styling.

### PR DESCRIPTION
**Pull request by joelachance**
This would eventually resolve #86.

The current tab layout doesn't look good for mobile, and has some additional shortcomings.
In this PR, I've added UI Kit tabs, moved each tabs' content into its own partial, and updated some of the styling.

~~This still to be done here:~~
* ~~Update content for mobile. This would be for 'Visualization', 'Data Science', 'Machine Learning'. Move images to showcase them a bit more!~~
* ~~Add carousel for 'Scientific Domains' and 'Array Libraries' tabs (i.e. slideshow through the logos and links, vs. rendering all at once)~~

I'm hoping to get feedback on what's been done so far before moving forward.

Last thing to note: I think the content in the homepage isn't dispersed very equally.  Our 'in a nutshell' section is much simpler than our tabs, and feels a bit light in comparison. I'd like to suggest we try to compress what we have for the tabs so it's a little easier for people just visiting the site for the first time to glance over, or perhaps distribute to another section? It would be great to hear what others think! (I hope no offense taken here, I know a lot of effort has gone into tab content to date!)

### CODE REVIEW

**Comment by joelachance** [comment]
I made a fix to the content width for all tabs. The title should be identical to 'Key Features' now, but if not I can fix those soon.

Everything else looks like a content change-- I created a ticket specifically for those here: https://github.com/numpy/numpy.org/issues/158

If everything else looks good, let's merge!

**Comment by shaloo** [comment]
Joel,  I'll take a look at this today and share additional inputs.

**Comment by shaloo** [comment]
@joelachance  - Will you be taking care of bullet #2 regarding tab title alignment with the text in the tab below?

**Comment by joelachance** [comment]
@shaloo I'll take care of #2! It's on my list.

**Comment by joelachance** [comment]
Fixed some padding, let me know what everyone thinks.

**Comment by rgommers** [comment]
Or, maybe I should review more carefully before hitting the green button on a rebase - this just broke the styling of the "Key features" tiles.

**Comment by rgommers** [comment]
Fixed in commit 0a66c2211f05, lost one CSS include in the rebase

**Pull request merged**
