### PR TITLE
Fixes #gh-223 color palette update as per #gh-33 in infographics for …

### PR DESCRIPTION
**Pull request by shaloo**
…data science ecosystem tab

#### Deployed URL

http://numpy-<pr_number>.surge.sh/

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @shaloo. I like the new image, colors are much cleaner and layout improved as well:

image

I did notice that both images became way larger. Is it possible to shrink them a little, >1 MB each is a bit heavy.

**Comment by shaloo** [comment]
> Thanks @shaloo. I like the new image, colors are much cleaner and layout improved as well:
> 
> image
> 
> I did notice that both images became way larger. Is it possible to shrink them a little, >1 MB each is a bit heavy.

Good catch.  Fixed image size.  Also provided a way to click and view zoomed image (same image) Thanks.

**Comment by rgommers** [comment]
LGTM now, merged. Thanks @shaloo!

**Comment by rgommers** [comment]
One other question: what format are the originals in? It would be good to store those as well, in case we need to edit them in the future.

**Comment by shaloo** [comment]
image format is png.  The same image is linked for 'click-open-in-new tab' action.  This one shows up image on full tab space of the browser window.

**Comment by rgommers** [comment]
But you can't edit these right? You must have made them in some drawing program, or Powerpoint/Keynote?

**Comment by shaloo** [comment]
Oh I did not get your original query.  Got it now.  These pngs are generated using powerpoint.  I have a full deck with all NumPy infographics generated so far.  It is in pptx format.  Where would you like me to check that it.  It keeps getting updated/new-items-added periodically.

**Comment by rgommers** [comment]
I think adding it to https://github.com/numpy/archive would be best. Big files that get updated are fine for that repo.

**Comment by shaloo** [comment]
ok, will do that right away.

**Pull request merged**
