### PR TITLE
MAINT: clean up NA-overview doc.

### PR DESCRIPTION
**Pull request by rgommers**
It was instead added as a NEP to the numpy repo in
https://github.com/numpy/numpy/pull/12017.

### CODE REVIEW

**Comment by charris** [comment]
Thanks Ralf.

**Comment by mattip** [comment]
The PR has been merged but was the site regenerated? I still see the file that was removed at http://www.numpy.org/NA-overview

**Comment by mattip** [comment]
Ping. The removed document is [still visible](http://www.numpy.org/NA-overview)

**Comment by rgommers** [comment]
will redeploy later when I have access to my regular desktop. there's no hurry though, this doesn't hurt at all.

**Comment by stefanv** [comment]
I redeployed; it's gone now.

**Comment by rgommers** [comment]
thanks!

**Comment by pllim** [comment]
Hello. I just noticed the broken link of http://www.numpy.org/NA-overview.html , which is mentioned in Astropy doc. A redirect would have been nice but I am glad I found this PR anyway.

**Comment by rgommers** [comment]
sorry @pllim - this stuff lives on a server that we have had some trouble with (no or limited admin rights), adding redirects is tricky. glad you resolved the issue

**Pull request merged**
