### PR TITLE
Update content of Data Science tab

### PR DESCRIPTION
**Pull request by rgommers**
Follow up to gh-242, alternative to gh-262. The content rewrite and inclusion of more relevant libraries attempts to make this sound natural, sketch the breadth of the Python data science offerings,
and keeps some of the tools like DVC and MLFlow that beginning to intermediate data scientists really need to learn about.

It does shrink the amount of content to a more reasonable size:

image

### CODE REVIEW

**Comment by bjnath** [comment]
That's nice, more info but doesn't seem dense.

How about this for the second paragraph (HTML coding is underneath):

At high data volumes, tools like <a href="https://dask.org">Dask</a> or <a href="https://ray.io/">Ray</a> are designed to scale. Production environments require data versioning (<a href="https://dvc.org">DVC</a>), experiment tracking (<a href="https://mlflow.org">MLFlow</a>), and workflow automation (<a href="https://airflow.apache.org">Airflow</a> and <a href="https://www.prefect.io">Prefect</a>).</p>

**Comment by rgommers** [comment]
Thanks @bjnath, that phrasing sounds better than mine, I've taken it over.

**Comment by rgommers** [comment]
In it goes

**Comment by bjnath** [comment]
Do you like "stable production **deployments** rely on" ( or "stable production deployment relies on")?

**Comment by rgommers** [comment]
`deployments rely` is maybe slight better?

**Comment by bjnath** [comment]
I'm happy with that.

**Pull request merged**
