### PR TITLE
Adds a news section

### LINKED ISSUE #219: Add News Section
Add “News” section to the home page, right below the "Get Started" button, to share announcements about the NumPy project development milestones, community initiatives, events, etc.

### PR DESCRIPTION
**Pull request by joelachance**
Resolves #219.

@InessaPawson, I wasn't sure about layout here. Do you have an example we should emulate?
I'm assuming we might tackle content in another ticket.

### CODE REVIEW

**Comment by InessaPawson** [comment]
> @InessaPawson, I wasn't sure about layout here. Do you have an example we should emulate?

@joelachance I quite like the news section here: https://kotlinlang.org, which is a .svg linking to a news article. We won't be linking to anything for now. 

> I'm assuming we might tackle content in another ticket.

Yes, I’ll take care of the content/image in a separate PR.

**Comment by InessaPawson** [comment]
> Thanks @joelachance! Just checking, is the smaller font and not all-uppercase on purpose here?

@rgommers It's just a placeholder, none of it will show. I’ll submit a PR with an image shortly.

**Comment by joelachance** [comment]
@rgommers, @InessaPawson is correct, simply a placeholder. If we keep the title, we can uppercase it with: `text-transform: uppercase;`

**Comment by InessaPawson** [comment]
Just an image for now: 

numpynews_warmblack

This is how it looks in a prototype: https://github.com/numpy/numpy.org/pull/221#issuecomment-620559287

@rgommers I need your input for the content of this section. Once everything is confirmed, I'll create a .svg version and submit a PR.

**Comment by joelachance** [comment]
Merging here, continuing work on PR #221.

**Pull request merged**
