### PR TITLE
WIP: Replaced content with auto-gen .md from pandoc.

### PR DESCRIPTION
**Pull request by rossbar**
NOTE: The new files were generated directly from docx to md via
pandoc - do not expect them to be correct!

Also note, the markdown is pandoc-flavored.

### CODE REVIEW

**Comment by rossbar** [comment]
The documents were converted with pandoc:

```console
pandoc -f docx -t markdown -o <filename>.md <filename>.docx
```

**Comment by rgommers** [comment]
Thanks @rossbar 

> `pandoc -f docx -t markdown -o <filename>.md <filename>.docx`

@shaloo I'm not sure if you were already working on this. If so, perhaps this Pandoc command can be of use (or maybe you had figured out something similar already). If you did start, this WIP PR may not be needed. Otherwise, it may be useful. Please let me know what you prefer.

**Comment by shaloo** [comment]
@rgommers - Yes, pandoc is a good 'first step' for conversion.  However, the output (more often than not) cannot be directly used (md, rst) and needs some manual curation (layout etc).  I'll stop any further update on this until it shows up in master and then curate (if needed).

**Comment by rgommers** [comment]
This turned out to not be the optimal way to do this conversion. @InessaPawson has been porting this content in a more piecemeal fashion. So I'll close this PR. Thanks again though @rossbar!

**Pull request closed without merging**
