### PR TITLE
Use scientific-python-hugo-theme

### LINKED ISSUE #475: factoring out the theme
@stefanv and I recently ported scipy.org to the new numpy.org theme (https://github.com/scipy/scipy.org/pull/413).  At first, we just manually copied over the files https://github.com/scientific-python/scipy.org-new/commit/7dda713c97330ff6e2e05cd939f4d919f15cb77c.  We started to think about using it for other sites (e.g., I would like to use this theme for https://scientific-python.org and https://networkx.org).  So we extracted the numpy.org theme to https://github.com/scientific-python/scientific-python-hugo-theme/ and used it for the new scipy.org site (https://github.com/scientific-python/scipy.org-new/pull/15).

Would you be interested in a PR to this repo to use https://github.com/scientific-python/scientific-python-hugo-theme/?  @stefanv and I are willing to help support this theme as part of the https://scientific-python.org project for a few years.  We would like to recruit a core developer team to help develop this theme.  Would any of you be interested in being a core developer of  https://github.com/scientific-python/scientific-python-hugo-theme/?

How should we proceed?  Maybe we should organize a short conference call to discuss how to move forward.

### PR DESCRIPTION
**Pull request by jarrodmillman**
Closes  #475.

This is a new theme copied from numpy.org so that multiple projects in the ecosystem can share the same look and feel.  This should not change the https://numpy.org website.

### CODE REVIEW

**Comment by jarrodmillman** [comment]
I believe someone needs to configure deploy keys so the scientific-python-hugo-theme submodule repository can be linked in ssh format:  https://docs.netlify.com/configure-builds/repo-permissions-linking/#deploy-keys

**Comment by rgommers** [comment]
> I believe someone needs to configure deploy keys so the scientific-python-hugo-theme submodule repository can be linked in ssh format: https://docs.netlify.com/configure-builds/repo-permissions-linking/#deploy-keys

A `https://` submodule link will work even if you have 2FA enabled (I just verified this), while SSH cloning will fail for most beginning contributors. I believe it's best practice to use `https://` here, so can you change this back?

**Comment by stefanv** [comment]
> @stefanv the footer is duplicated on the front page screenshot

See 338a1d4

**Comment by rgommers** [comment]
@jarrodmillman I'm offline for a few days so no time to merge or review in detail. But you all can go ahead without me. I've added you and @stefanv to the web team, so if both of you are happy then please go ahead and merge this. Deployment should work I believe, the GH Action uses `submodules: true` already.

**Review by stefanv — APPROVED** [review]
I've clicked through the site and I don't see any obvious regressions :+1:

**Pull request merged**
