### PR TITLE
MAINT: add Numeric manual link

### PR DESCRIPTION
**Pull request by tylerjereddy**
@stefanv asked me to add a historic link to the `Numeric` manual re: being helpful for citing in the SciPy manuscript.

### CODE REVIEW

**Comment by stefanv** [comment]
I think we should commit the actual PDF, so that we have our own copy hosted.

**Comment by tylerjereddy** [comment]
Ok, revised to put the PDF in the static path and link to it with a download directive

**Comment by stefanv** [comment]
Great, thanks.

**Comment by rgommers** [comment]
This doesn't build correctly for me, there's no link and a warning:
```
/home/rgommers/code/other/numpy.org/www/old_array_packages.rst:38: WARNING: 
download file not readable: /home/rgommers/code/other/numpy.org/www/_static/numeric-manual.pdf
```
(line number is after rebase onto master)

**Comment by rgommers** [comment]
Hmm, I shouldn't try to review when I'm dead tired. I messed up a rebase, sorry about that. LGTM, merging now.

**Comment by stefanv** [comment]
:) Thanks folks!

**Comment by rgommers** [comment]
`:download:` is documented to put files in `_downloads/` (see https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-download), however Sphinx seems to have messed this up. It's now: https://numpy.org/_downloads/768fa66c250a0335ad3a6a30fae48e34/numeric-manual.pdf (with Git commit hash changing per build).

Either way this link wasn't on our radar and will be wiped out when we change to the new Hugo based website. I'll put it on Figshare.

**Comment by rgommers** [comment]
Okay, Zenodo is better - Figshare is difficult to change dates to be in the past, author names, etc. Here it is: https://doi.org/10.5281/zenodo.3599566

**Pull request merged**
