### PR TITLE
Issu 104 al

### LINKED ISSUE #104: Content: Array Libraries tab
Create content for Landing page Ecosystem Tab "Array Libraries"

### PR DESCRIPTION
**Pull request by shaloo**
#### Deployed URL

https://pr-<pr_number>-numpy.surge.sh

### CODE REVIEW

**Comment by shaloo** [comment]
This is how the new content shows up on localhost:1313

Screenshot 2019-12-16 at 2 11 07 PM

**Comment by rgommers** [comment]
This looks nice! My one question right now is if it's possible to find logos for Xarray, XND, Dask and CuPy without the gray background.

**Comment by shaloo** [comment]
Thx Ralf for the feedback. Yes, got all four.

**Comment by shaloo** [comment]
@rgommers, is this good to go now?

**Comment by rgommers** [comment]
Looks nice now! I'll try and fix the merge conflicts now and then push the fix.

**Comment by rgommers** [comment]
Merged, thanks @shaloo!

**Pull request merged**
