### PR TITLE
additional aria-labels

### LINKED ISSUE #118: Website Accessibility
We need to check that the new website can be navigated with browser accessibility tools.

- [x] Test happy paths and make sure there aren't any bugs when navigating with accessibility tools.

### PR DESCRIPTION
**Pull request by joelachance**
Resolves #118

### CODE REVIEW

**Comment by rgommers** [comment]
@joelachance is the WIP in the title on purpose? This looks straightforward enough

**Comment by joelachance** [comment]
@rgommers The WIP title was indeed on purpose. I wasn't sure if @MarsBarLee wanted to give this a once-over or not, but I do think it's fine to merge if we'd like it in! I'll leave it up to you.

**Comment by rgommers** [comment]
Merged, thanks @joelachance

**Comment by rgommers** [comment]
@MarsBarLee please feel free to comment or send a follow-up. Just want to get as much as possible in now:)

**Comment by MarsBarLee** [comment]
Looks good to me!

**Pull request merged**
