### PR TITLE
crowdin setup and language dropdown

### PR DESCRIPTION
**Pull request by Shekharrajak**
- crowdin config file added
- project ID and api key is in environment variable

### CODE REVIEW

**Comment by joelachance** [comment]
Looks good here too! I'm assuming we need a dropdown to select a language?

**Comment by Shekharrajak** [comment]
> Looks good here too! I'm assuming we need a dropdown to select a language?

Yes! I am working on it. Once a language is selected all the links URL should be changed accordingly. i.e. if Hindi is selected then URL for `/about` should be `/hi/about`

**Comment by Shekharrajak** [comment]
Crowdin machine translation: https://github.com/numpy/numpy.org/pull/62

**Comment by Shekharrajak** [comment]
Important links: https://gohugo.io/content-management/multilingual/

**Comment by Shekharrajak** [comment]
Demo for the language dropdown: 


hugo-lang-gif


demo URL : http://pr-61-numpy.org-newsite.surge.sh/

**Comment by Shekharrajak** [comment]
For the demo purpose I have used 3 languages : English, Dutch and Hindi. 
Note: Only Dutch language is translation is done using the crowdin machine translator. Hindi will look same as English (since it is not at all translated).

Default folder is `content/en`. 

So I think we should use the `en` folder for the content and remove the `content/*.md` files.

**Comment by rgommers** [comment]
dropdown looks good!

**Comment by Shekharrajak** [comment]
Now all the URLs will come according to the language selected. 🎉

**Comment by Shekharrajak** [comment]
We can merge this PR for now.

**Comment by rgommers** [comment]
Ah actually the Hindi translation is already in here.

I like the look of this @Shekharrajak

**Pull request merged**
