### PR TITLE
Add an explicit anchor to releases section

### PR DESCRIPTION
**Pull request by steppi**
#### Brief description of what is fixed or changed
This PR adds an explicit anchor to the releases section of `news.md`. This is required for the link to work with translated content.

cc @rgommers @melissawm

### CODE REVIEW

**Comment by steppi** [comment]
Actually, I'm starting to think it might not be viable to keep translations for `news.md` up to date. Looking at the [history](https://github.com/numpy/numpy.org/commits/main/content/en/news.md) , it seems to update 1-2 times per month. Across multiple projects and across multiple language, the person hours could build up; I think there might be better uses for the effort.

Currently there's a link to  `news.md` through this top button

image

but maybe for the translated content it's better just to link to `install.md` for like was done on `main` prior to https://github.com/numpy/numpy.org/commit/416b4fc945dc0df1ac474498bdf76fae3fd9c9a2. It might be difficult to keep translators in sync about this though.

**Comment by rgommers** [comment]
> Actually, I'm starting to think it might not be viable to keep translations for `news.md` up to date. Looking at the [history](https://github.com/numpy/numpy.org/commits/main/content/en/news.md) , it seems to update 1-2 times per month. Across multiple projects and across multiple language, the person hours could build up; I think there might be better uses for the effort.

There's not nearly as many actual content updates though; most of the comments are just one-line entries for bug fix releases. How about splitting the release updates off into a separate `.md` file that is pulled in at the bottom of the news page but explicitly excluded from translating efforts in `crowdin.yml`?

**Review by rgommers — APPROVED** [review]
Adding this anchor seems like a straightforward fix. Thanks Albert.

**Comment by stefanv** [comment]
All markdown headings already have anchors generated, so this should not be necessary. Click in the navigation table on the left, and copy the URL, which will now contain the anchor.

**Comment by rgommers** [comment]
> Then I guess we just don't want to link to the releases from the translated content?

Either that, since there's not too much value in this list at the bottom of the news page, or just automate it somehow in a build step. There's no new translations to be done in this kind of thing:

```
NumPy 1.25.1 ([release notes](https://github.com/numpy/numpy/releases/tag/v1.25.1)) – 8 Jul 2023.
NumPy 1.24.4 ([release notes](https://github.com/numpy/numpy/releases/tag/v1.24.4)) – 26 Jun 2023.
NumPy 1.25.0 ([release notes](https://github.com/numpy/numpy/releases/tag/v1.25.0)) – 17 Jun 2023.
NumPy 1.24.3 ([release notes](https://github.com/numpy/numpy/releases/tag/v1.24.3)) – 22 Apr 2023.
NumPy 1.24.2 ([release notes](https://github.com/numpy/numpy/releases/tag/v1.24.2)) – 5 Feb 2023.
NumPy 1.24.1 ([release notes](https://github.com/numpy/numpy/releases/tag/v1.24.1)) – 26 Dec 2022.
NumPy 1.24.0 ([release notes](https://github.com/numpy/numpy/releases/tag/v1.24.0)) – 18 Dec 2022.
NumPy 1.23.5 ([release notes](https://github.com/numpy/numpy/releases/tag/v1.23.5)) – 19 Nov 2022.
NumPy 1.23.4 ([release notes](https://github.com/numpy/numpy/releases/tag/v1.23.4)) – 12 Oct 2022.
NumPy 1.23.3 ([release notes](https://github.com/numpy/numpy/releases/tag/v1.23.3)) – 9 Sep 2022.
```

all it needs is a one-off translation of the words "release notes".

**Comment by stefanv** [comment]
Ah, gotcha! Yes, I remember having to fix that for other languages in the Hugo update

> I think the anchor name depends on the header title, so after translation the link no longer works.

Ah, gotcha! Yes, I think I had to fix that for other languages in the Hugo 114 update as well.

Another way to spell this would be:

```
## My Heading {#anchorname}
```

**Comment by steppi** [comment]
> Another way to spell this would be:
> 
> ```
> ## My Heading {#anchorname}
> ```

Nice! I like this syntax better.

**Pull request merged**
