### PR TITLE
Remove Twitter links in English version

### PR DESCRIPTION
**Pull request by star1327p**
#### Brief description of what is fixed or changed

1. Replaced Twitter with X, including the links https://x.com/numpy_team .

2. Updated the Youtube channel to a shorter URL https://www.youtube.com/@NumPy_team .

### CODE REVIEW

**Comment by seberg** [comment]
Thanks for looking into this.  xref https://github.com/numpy/numpy/pull/28036 (twitter is in the NumPy readme).

We removed the main X/twitter link in https://github.com/numpy/numpy.org/pull/767 (we never used it that much), so we may even just want to remove it.  @InessaPawson what do you prefer?

**Comment by InessaPawson** [comment]
@seberg +1 on removing the mention and the link to the NumPy X account.

**Comment by InessaPawson** [comment]
@star1327p Thank you for working on this PR! Please note that the translations on numpy.org are done by our translations team via Crowdin. Please remove all pending changes for any language versions other than English.

**Comment by star1327p** [comment]
@seberg @InessaPawson Thank you both for reviewing! I have removed the Twitter link in the English version, and reverted my changes in the other languages.

**Pull request merged**
