### PR TITLE
announce the NumPy 1.24.2 release

### PR DESCRIPTION
**Pull request by charris**

### CODE REVIEW

**Comment by stefanv** [comment]
Thanks, Chuck! Would you like this to show up on the frontpage as well?

**Comment by stefanv** [comment]
OK, I see, just the list of releases was updated. Is that what you want?

**Comment by charris** [comment]
>Is that what you want?

Yep. We only do the extras for the first release in a cycle, and sometimes @rgommers edits things. If folks want more, they should mention it in the NumPy issues.

**Comment by stefanv** [comment]
:+1:

**Pull request merged**
