### PR TITLE
Set Twitter card image to PNG

### PR DESCRIPTION
**Pull request by ErnestoFGonzalez**
Fixes gh-591

- add `twitter-image.jpg` asset to static dir.
- Set `twitter-image.jpg` to `images` param in `config.yaml` to be used as image for Twitter card (see [Configuring Twitter Cards](https://gohugo.io/templates/internal/#configure-twitter-cards) in Hugo docs).

### CODE REVIEW

**Comment by ErnestoFGonzalez** [comment]
I'm getting 
```
INFO:  Page fetched successfully
INFO:  10 metatags were found
INFO:  twitter:card = summary_large_image tag found
INFO:  Card loaded successfully
```

on Twitter Card Validator but the card preview is not rendering.

**Comment by ErnestoFGonzalez** [comment]
> I'm getting
> 
> ```
> INFO:  Page fetched successfully
> INFO:  10 metatags were found
> INFO:  twitter:card = summary_large_image tag found
> INFO:  Card loaded successfully
> ```
> 
> on Twitter Card Validator but the card preview is not rendering.

Looks like the 1x1 dimensions are not supported. Let me fix this.

**Comment by ErnestoFGonzalez** [comment]
I think this one should work. You won't see it in the preview because of the template expects the image to be at `https://numpy.org/images/twitter-image.jpg`, and the preview url is `https://deploy-preview-609--numpy-org.netlify.app`. 

Inspecting the head of the page you can see
```
<meta name="twitter:image" content="https://numpy.org/images/twitter-image.jpg">
```

**Comment by stefanv** [comment]
Thanks, @ErnestoFGonzalez!

**Comment by ErnestoFGonzalez** [comment]
> Thanks, @ErnestoFGonzalez!

Glad to help, @stefanv! I'll be trying to help on some other issues. Let me know if you want me to prioritise some.

**Pull request merged**
