### PR TITLE
Change icon colors in Sience Domains tab of Ecosystem section

### PR DESCRIPTION
**Pull request by ErnestoFGonzalez**
#### Brief description of what is fixed or changed

- Fixes gh-478.
- Set icon colors in Science domain tab of Ecosystem section to `#013243`.

Following is a screenshot of the result:

Screenshot 2022-10-28 at 00 17 43

### CODE REVIEW

**Comment by stefanv** [comment]
If we're updating the icon colors, should we update the headings to match? Also, the icons are currently centered which looks a bit weird: how about left alignment, as with the headings?

**Comment by ErnestoFGonzalez** [comment]
> If we're updating the icon colors, should we update the headings to match? Also, the icons are currently centered which looks a bit weird: how about left alignment, as with the headings?

Yeah, that'd look better. I'll push another commit.

**Comment by ErnestoFGonzalez** [comment]
I like it better this way. What do you think @stefanv?

**Comment by stefanv** [comment]
That looks good! I see `casestudies.css` also custom specifies color. I recommend refactoring that into a variable that is reused elsewhere.

Actually, looking at the theme CSS you already have:

```
  --colorPrimaryDark:  rgb(1, 50, 67);
```

which you can reuse as:

```
color: var(--colorPrimaryDark);
```

**Comment by ErnestoFGonzalez** [comment]
> That looks good! I see `casestudies.css` also custom specifies color. I recommend refactoring that into a variable that is reused elsewhere.
> 
> Actually, looking at the theme CSS you already have:
> 
> ```
>   --colorPrimaryDark:  rgb(1, 50, 67);
> ```
> 
> which you can reuse as:
> 
> ```
> color: var(--colorPrimaryDark);
> ```

Right! I missed that. 
Done for `case studies.css` and `tabs.css`. 
I see some usages of the hex color in `layouts/shortcodes/numfocus.html`. Want me to see if I can use the variable here?

**Review by stefanv — APPROVED** [review]

**Comment by stefanv** [comment]
Don't worry about the NF partial, I think this is good to go!

**Pull request merged**
