### PR TITLE
Update the NumPy Maintainers list

### PR DESCRIPTION
**Pull request by InessaPawson**
Adding @Qiyu8, @ganesh-k13, @BvB93, @seiko2plus, @person142 to the Maintainers list.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @InessaPawson. The preview shows that the new people aren't yet showing up on the Team page. It was/is necessary to run a script in `scipts/gallery/` so that https://github.com/numpy/numpy.org/blob/master/scripts/gallery/cache/numpy_team.context is updated with the actual data. 

That's a bit annoying indeed, it's being fixed by @stefanv. Stefan, this repo isn't converted to your new gallery style yet right?

**Comment by charris** [comment]
What is the status of this?

**Comment by shaloo** [comment]
> Thanks @InessaPawson. The preview shows that the new people aren't yet showing up on the Team page. It was/is necessary to run a script in `scipts/gallery/` so that https://github.com/numpy/numpy.org/blob/master/scripts/gallery/cache/numpy_team.context is updated with the actual data.
> 
> That's a bit annoying indeed, it's being fixed by @stefanv. Stefan, this repo isn't converted to your new gallery style yet right?

We did not want to use GitHub API multiple times unless necessary to fetch team picture and other details for the card UX. Hence the script was supposed to be run only when the team was to be updated .  GitHub API had an upper limit on how many times you could run them in a 24 hr period hence this approach (back then).  Is there anything that I can help with if the requirements have changed now?  I created the original team page with script et all based on guidance from some NumPy contributors.

**Comment by shaloo** [comment]
> > Thanks @InessaPawson. The preview shows that the new people aren't yet showing up on the Team page. It was/is necessary to run a script in `scipts/gallery/` so that https://github.com/numpy/numpy.org/blob/master/scripts/gallery/cache/numpy_team.context is updated with the actual data.
> > That's a bit annoying indeed, it's being fixed by @stefanv. Stefan, this repo isn't converted to your new gallery style yet right?
> 
> We did not want to use GitHub API multiple times unless necessary to fetch team picture and other details for the card UX. Hence the script was supposed to be run only when the team was to be updated . GitHub API had an upper limit on how many times you could run them in a 24 hr period hence this approach (back then). Is there anything that I can help with if the requirements have changed now? I created the original team page with script et all based on guidance from some NumPy contributors.

Here is how the script works:  Refer to comments in the script for details.

1.  You run NumPy_team.py script with the yaml file containing list of new contributors in the specified format (see team.yml file).  This will fetch updated info for all listed contributors and save it in a context file cache/contextfile by default.

2. You run NumPy_team.py script again, this time set --stored-context option with dir/pathname to the context file and it will generate team.html page.  The Hugo subsystem refers to this page in static/gallery directory.  If you do not specify the --target option in script run, by default this html page is generated in static/gallery directory.

Hope this helps.  This script is based on similar approach taken by pandas_web project that Ralf guided me to.

**Comment by jarrodmillman** [comment]
See #510.

**Comment by jarrodmillman** [comment]
Closing b/c #510 merged (reopen if this was an error on my part).

**Pull request closed without merging**
