### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Shekharrajak**
Enjoy!

### CODE REVIEW

**Comment by joelachance** [comment]
Nice, looks good!

**Comment by joelachance** [comment]
Actually, question here for everyone-- do you think we should default to English, as in we shouldn't nest it under `/en`? Or keep as it is here?

No preference here.

**Comment by Shekharrajak** [comment]
> Actually, question here for everyone-- do you think we should default to English, as in we shouldn't nest it under `/en`? Or keep as it is here?
> 
> No preference here.

I think it by default it can be in `en` folder. May be `en` folder is not needed since our default language is English. I created it just for testing.

**Comment by Shekharrajak** [comment]
I am merging it (target branch is gsod-newsite https://github.com/numpy/numpy.org/pull/61 ) to test later parts.

**Comment by rgommers** [comment]
not having `/en` but just having `numpy.org` be English and `numpy.org/fr` French would be a little cleaner I think.

**Comment by Shekharrajak** [comment]
> not having `/en` but just having `numpy.org` be English and `numpy.org/fr` French would be a little cleaner I think.

Yes, default folder is `en` and all the URLs will look `numpy.org` (not umpy.org/en) 🎉

**Comment by rgommers** [comment]
awesome:)

**Pull request merged**
