### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by InessaPawson** [comment]
Thank you, @rgommers!

**Comment by rgommers** [comment]
This looks a little off. I may have set up some integration, but I did not open this PR so it shouldn't look like it comes from me. A previous one had a bot handle: gh-793.

@steppi any idea what happened here?

**Comment by steppi** [comment]
My apologies @InessaPawson and @rgommers. This PR should not have been merged and it's entirely my fault. It was generated by Crowdin and has commits for all updates made by translators within the Crowdin UI. @rgommers set up the integration, so he appears as the author. The bot handle for gh-793 is a red herring, that PR was generated by one of our GitHub workflows, and takes commits from the Crowdin PR branch `l10n_main` for only one particular language, puts them in a new branch and PRs that branch. As far as I know, the only way to make the author of the Crowdin PR to appear as a bot would be to create a "bot" account with admin privileges on this repo and use it to set up the Crowdin integration.

On translations repos for other projects I added a `do-not-merge` label and a CI job that fails if the `do-not-merge` label is presents, with merging disallowed if the job fails. See  https://github.com/Scientific-Python-Translations/pandas-translations/pull/56. I guess because translations for this repo aren't managed in the scientific-python-translations organization, I forgot to set  up the `do-not-merge` thing here. I'll do that, and also look into reverting these changes.

**Comment by rgommers** [comment]
Thanks for the context @steppi. That sounds like a good plan.

**Pull request merged**
