### PR TITLE
Updates colors to Warm Black

### LINKED ISSUE #246: Change the color of the `hero-title` font and footer background
Change the color of the `hero-title` font and background color of the footer to Warm Black      (#013243) to match the rest of the dark elements.

### PR DESCRIPTION
**Pull request by joelachance**
Resolves #246

### CODE REVIEW

**Comment by joelachance** [comment]
Screen Shot 2020-05-22 at 10 44 37 PM
Screen Shot 2020-05-22 at 10 44 31 PM

**Comment by rgommers** [comment]
Thanks @joelachance. I pushed a fix for the merge conflict here after merging the mobile CSS PR.

Colors look good, I do have two small suggestions:
- the link hover color in the footer turned blue now, keeping it white (same as the news bar) would look better I think
- the vertical alignment between the links section and the rightmost column is a little odd. would it be possible to align the top of `Sign up for the latest NumPy news` with `Get Help`?

**Comment by joelachance** [comment]
@rgommers something happened here, do we want the footer links top-aligned? I feel like these were vertically aligned in the center previously.

I'm going to make the hover color white, but keep the underline. Does that make sense?

**Comment by rgommers** [comment]
> @rgommers something happened here, do we want the footer links top-aligned? I feel like these were vertically aligned in the center previously.

Top-aligned sound good to me. I think they weren't perfectly aligned before, but the offset got more pronounced - it immediately caught my eye and didn't before.

> I'm going to make the hover color white, but keep the underline. Does that make sense?

Thanks, I like that - and that's also how the News bar works right now.

**Comment by joelachance** [comment]
Ok @rgommers, we should be in good shape here.

**Comment by rgommers** [comment]
Thanks @joelachance! Still a tiny bit unequal it looks like, but way better:

image

**Pull request merged**
