### PR TITLE
Make the "deploy" GitHub Action works on master

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
That did trigger, but the domain isn't printed and the deploy to `pr-74-numpy.org-newsite.surge.sh` failed:

image

`pr-71-numpy.org-newsite.surge.sh` worked, but I'm not sure if I'm missing anything here. @Shekharrajak any thoughts?

**Comment by Shekharrajak** [comment]
It looks like it is not able to take surge login id and surge token from the github secrets (environment variable). it should show `**` front of surge login and token.

**Comment by Shekharrajak** [comment]
I am not sure why did it trigger but I added the master branch in push and PR trigger list: https://github.com/numpy/numpy.org/pull/76

**Comment by Shekharrajak** [comment]
Try to get help: https://github.com/sintaxi/surge/issues/386

**Comment by Shekharrajak** [comment]
Worked for #77 PR also : https://pr-77-scipy-sphinx-theme-v2.surge.sh

**Comment by Shekharrajak** [comment]
I am suspecting that SURGE_LOGIN and SURGE_TOKEN is not picked since [here](https://github.com/numpy/numpy.org/pull/74/checks?check_run_id=316137404#step:3:116) it is printing nothing. It should print `***` like [here](https://github.com/numpy/numpy.org/pull/77/checks?check_run_id=316118983#step:3:116).

The question is why?

**Comment by Shekharrajak** [comment]
Related PR #79

**Pull request closed without merging**
