### PR TITLE
Web accessibility - Contrast ratio for WCGA AA

### PR DESCRIPTION
**Pull request by MarsBarLee**
Increased contrast ratio between words and background by changing the color of links in the Key Features, Ecosystem sections and footer.

This meets the contrast ratio a WCGA AA rating. Web Content Accessibility Guidelines and its rating range from A to AAA.

I used WebAIM and WAVE tools to check the rating.

**Questions**
I used ! important in the internal css to override external linked css from UiKit. I know ! important isn't generally recommended but it's how I was able to override the external css. **Does anyone know another way or is using ! important here OK?**

**Can I remove the empty h3 tag in footer.html and empty title in config.yaml?** Or is there a title planned for these sections?
image

### CODE REVIEW

**Comment by MarsBarLee** [comment]
I'm looking into the error 'sudo: hugo: command not found' in the Travis CI. 

When I do git status, it tells me that 'modified:   themes/hugo-fresh (modified content)'. I didn't commit that change since I don't think I made any changes in the theme or wanted to.

Could the modified theme be related to the CI error I'm getting?

**Comment by joelachance** [comment]
> Does anyone know another way or is using ! important here OK?

If you can write a more specific CSS rule, you won't need `!important`. I've used it a couple of times just because sometimes those global rules are tough to circumvent (and I'm a bit lazy ;)) 

> Can I remove the empty h3 tag in footer.html and empty title in config.yaml?

If it's not being used, sure!

> Could the modified theme be related to the CI error I'm getting?
@rgommers? Any thoughts here?

**Comment by MarsBarLee** [comment]
@joelachance Actually, I think I figured how to override without using ! important last night, and the commits here don't use ! important. Solved it already, haha. I also pushed another commit to remove the headings.

**Comment by rgommers** [comment]
> > Could the modified theme be related to the CI error I'm getting?
> 
> @rgommers? Any thoughts here?

It's flaky like crazy, just ignore it for now. I've seen `sudo: hugo: command not found` on a number of other PRs, it's not related the changes in this PR.

**Comment by MarsBarLee** [comment]
@rgommers Ok! Do I wait for the build to work later then?

**Comment by rgommers** [comment]
Just ignore it, if you think the PR is ready then we can review and merge

**Pull request merged**
