### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
Hi. I'm just letting you guys know. I translated almost docs (except terms.md) in Japanese. 
I think another Japanese speaker should check these, but I hope these translations help NumPy community.

**Comment by rgommers** [comment]
Whoa, amazing @AtsushiSakai! 

The interface says 77% complete:

image

If you go in you see that all translations are at 100% except for `about.md` at 96% and `terms.md` at 0%. I think removing `terms.md` from the files to translate is justified, because it's legal boilerplate that is good practice to have on the site but no user is actually going to read. It's really long, and I wouldn't want people to spend a lot of energy on that.

> I think another Japanese speaker should check these, but I hope these translations help NumPy community.

It will certainly help I think:) Let's try and find someone to proofread (I'll try via the mailing list first), and then deploy this.

Brazilian Portuguese is not far behind, there's 3-4 files to go. This will be great to finally launch!

**Comment by rgommers** [comment]
gh-408 should bring Japanese translation completeness to almost 100%, only 2 sentences in `about.md` left. I also sent you an invite so you have triage permissions on this repo @AtsushiSakai, in case that is helpful.

**Comment by rgommers** [comment]
image

**Comment by AtsushiSakai** [comment]
> I think removing terms.md from the files to translate is justified

I think that is good idea. Maybe if its translation is needed, someone who has legal knowledge should do that.

> It will certainly help I think:)

I'm happy to hear that. I will finish remaining soon (maybe next week).

**Comment by Qiyu8** [comment]
@rgommers As a chinese native speaker, Can I help with the chinese simplified translate work in case study part?

**Comment by rgommers** [comment]
> @rgommers As a chinese native speaker, Can I help with the chinese simplified translate work in case study part?

@Qiyu8 that would be awesome! There's info at https://github.com/numpy/numpy/wiki/Translations-of-the-NumPy-website on Crowdin. And the `config.yaml` file is best done via a regular PR - see https://github.com/numpy/numpy.org/pull/415 for an example.

Please let me know if anything isn't clear enough; some of the docs may still need improving.

(and I should really fix the last missing pieces in `config.yaml` so we can launch Japanese and Portuguese)

**Pull request closed without merging**
