### PR TITLE
Change the color of the icons on the Scientific Domains tab

### PR DESCRIPTION
**Pull request by ghost**
I have changed the color of logos with HEX CODE #13243 under the main issue of #474 and further raised by @MarsBarLee.

Icon color was black, now looks like:

image

The SVG files were also reformatted across multiple lines for readability.

### CODE REVIEW

**Review by InessaPawson — APPROVED** [review]

**Review by InessaPawson — CHANGES_REQUESTED** [review]
Great start, Vivek! Keep going! There are 16 icons in the Scientific Domains subsection. It would be nice if you change the color in all of them.
CORRECTION: there are 14 icons in the Scientific Domains subsection.

**Comment by new-vivek11** [comment]
in this directory : https://github.com/new-vivek11/numpy.org/tree/master/static/images/content_images/sc_dom_img

we have 15 files only - 14 of them are .svg files (whom i have modified in terms of color) and 1 file is a .py file which i did not change.

Not sure how to find the remaining 2 files of the 16 files (as mentioned above by @InessaPawson )

**Comment by new-vivek11** [comment]
It's always great to see one's first PR merged ! 🌻

**Comment by new-vivek11** [comment]
@rgommers yes it will be good once she takes a look at it @MarsBarLee

**Comment by MarsBarLee** [comment]
It looks great! I just have one issue: the icon for Graphs and Networks (sd6.svg) has a dark border around it.
This is how it looks [in the PR](https://github.com/new-vivek11/numpy.org/blob/master/static/images/content_images/sc_dom_img/sd6.svg):
image

This is how it looks usually, in the [current numpy.org version](https://github.com/numpy/numpy.org/blob/master/static/images/content_images/sc_dom_img/sd6.svg):
image

(I also realized that this image is cropped- that can be fixed in a future PR)

I think the change to spreading the SVG file across multiple lines is due to Adobe Illustrator SVG Export Plug-In. It could help a future contributor read and change the SVG via code instead of a graphic program. For example, changing the color by changing 'stroke:#013243'.

**Comment by new-vivek11** [comment]
I will look into it @InessaPawson and will give update on it soon.

**Comment by new-vivek11** [comment]
@InessaPawson @MarsBarLee 

I have changed the logo (sdg6.svg) .. look here : https://github.com/numpy/numpy.org/pull/483

**Pull request closed without merging**
