### PR TITLE
Fix navigation to other pages with recent Hugo.  Closes gh-50

### PR DESCRIPTION
**Pull request by rgommers**
Also updates to latest version of the Fresh theme.

### CODE REVIEW

**Comment by rgommers** [comment]
Okay I identified and fixed the navigation issue, but the fix is incomplete and CI is right to explain. The second commit could be wrong, it's still failing:
```
Error: Error building site: failed to render pages: render of "page" failed: "/app/layouts/_default/single.html:13:34": execute of template failed: template: _default/single.html:6:7: executing 
"_default/single.html" at <partial "css.html" .>: error calling partial: "/app/layouts/partials
/css.html:13:34": execute of template failed: template: partials/css.html:13:34: executing 
"partials/css.html" at <toCSS $cssOpts>: error calling toCSS: type map[string]interface {} not 
supported in Resource 
```

I don't actually know what I'm doing with this theming, so I'll leave it here for now. @joelachance if you could take this over, that would be awesome.

**Comment by joelachance** [comment]
I will look at this! Thank you for finding this fix, I hadn't had much luck with it.

**Comment by stefanv** [comment]
I am also running v0.58.3, but the build works for me.

**Comment by rgommers** [comment]
superseded by gh-59, closing

**Pull request closed without merging**
