### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Shekharrajak**
Enjoy!

### CODE REVIEW

**Comment by Shekharrajak** [comment]
@rgommers now it is generating the folder structure as expected.

**Comment by Shekharrajak** [comment]
We need to delete the `l10n_master` branch to make it consistent as discussed with the crowdin team.

**Comment by rgommers** [comment]
> We need to delete the `l10n_master` branch to make it consistent as discussed with the crowdin team.

I set the "delete head branches" option in the repo settings, so on merge the branch should be auto-deleted.

**Comment by rgommers** [comment]
That looks much better. The ML translation is pretty good. 

It also translations the pages like terms and conditions etc., we could possibly exclude those - not sure (maybe let's deal with that later if it's not super easy to do.

**Comment by rgommers** [comment]
Yep, that worked.

**Comment by rgommers** [comment]
I'll check the deployed Dutch site later, if that looks good then I think we're ready to get rid of it and switch to Mandarin.

**Comment by rgommers** [comment]
Hmm, that doesn't build for me:
```
Error: Error building site: "/home/rgommers/code/websites/numpy.org/content/hi/contribute.md:1:1": invalid YAML delimiter
```
@Shekharrajak have you seen that before?

The issue seems to be that header got changed from `---` to `- - -` in lines 1 and 3.

**Comment by rgommers** [comment]
Hmm, next issue:
```
Error: Error building site: "/home/rgommers/code/websites/numpy.org/content/nl/about.md:54:1": failed to extract shortcode: template for shortcode "figuur" not found
```
That makes sense, it translated the `figure` shortcode, which should be unchanged.

I'll revert this PR.

**Comment by rgommers** [comment]
Alright, I just removed this squash-merge commit from master, should be fine. So things to do:

1. Get rid of Hindi
2. Figure out why auto-translate messed up some `---` lines
3. Figure out why CI was green even though this doesn't even build and fix that.
4. Then retry with Dutch

**Comment by rgommers** [comment]
@Shekharrajak do you agree with the above plan? Could you tackle (1) and (3) first? That will make the rest easier.

**Comment by Shekharrajak** [comment]
> @Shekharrajak do you agree with the above plan? Could you tackle (1) and (3) first? That will make the rest easier.

Yeah! I will do that. CI is not configured for the build so we need to add it.

**Pull request merged**
