### PR TITLE
Page template

### LINKED ISSUE #88: Content Page Layout
- [x] Create a sidebar with shortcuts to headers inside the page
- [x] Add a 'Get Help?' link below the shortcuts
- [x] Add the footer to the content pages

The 'Get Help?' link should only render on the following pages:

- Install
- Documentation
- Learn
- Community
- Contribute

### PR DESCRIPTION
**Pull request by joelachance**
Resolves #88.

Adds sidebar to pages with shortcuts and a 'get help' link.
Adds footer to pages as well.

### CODE REVIEW

**Comment by rgommers** [comment]
Did you mean to leave this much space between main content and sidebar text? I'm not sure it looks the same on all browsers, this is with Firefox on Linux:

image

**Comment by rgommers** [comment]
The title of the Contribute page seems to have gone missing:

image

The whitespace does look better here. Still could be trimmed a little I think.

**Comment by rgommers** [comment]
The footer changes look good to me.

**Comment by joelachance** [comment]
I can take a look at this and resolve the merge conflicts.
I wasn't seeing that much white space last time I looked at this branch, but I agree, we don't want that much :)

**Pull request closed without merging**
