### PR TITLE
Re-arrange Github Actions yaml

### PR DESCRIPTION
**Pull request by joelachance**
Remove ticks around hugoVersion, re-arranges values to match the docs

### CODE REVIEW

**Comment by joelachance** [comment]
I think we're going to need to add `PERSONAL_TOKEN` to the secrets, but I'm not sure what that's supposed to be just yet. I need to look into that.

**Comment by mattip** [comment]
Did you see https://github.com/peaceiris/actions-hugo#%EF%B8%8F-create-your-workflow which does not use docker?

**Comment by joelachance** [comment]
I did! We were using that action previously before the first merge in this group. I wasn't finding any config to push to a different repository, so I was going for the easiest thing. We could stick with the peaceiris action, but we may need a token anyway to push the built code into a new repo, right?

**Comment by mattip** [comment]
Can we create a org-wide token that works in both repos?

**Comment by joelachance** [comment]
Ok, two things, @mattip @rgommers:
1. I removed `siteDir`. I don't think we need it since it builds into the root directory (i think?)
2. I added a personal access token from my account. it only has org permissions, nothing else. There's no way to generate an org token from what I've been finding online, it's not a thing for some reason.
 
It seems it made it past the githubToken error and died on attempting to `cd` into the siteDir, so I'm hoping these changes will work.

**Comment by rgommers** [comment]
> There's no way to generate an org token from what I've been finding online, it's not a thing for some reason.

Indeed. I believe the other way to do this is to create a dummy user (e.g., `numpy-deploy-bot`) and use that for such purposes. But it doesn't matter too much, happy to go with your token.

**Review by rgommers — APPROVED** [review]
Thanks @joelachance, let's give this a try.

**Comment by joelachance** [comment]
Sounds good! I don't mind, if something weird comes up and we need to change the token, i don't see that being a big problem.
Hopefully this works 🤞

**Comment by rgommers** [comment]
Still failing:
```
remote: Permission to numpy/numpy.github.com.git denied to joelachance.
```
Let me check that now.

**Comment by rgommers** [comment]
Hmm, you have write access and there's no branch protection rules on that repo. So it should have worked. That's the second time, after @mattip not being able to merge PRs on this repo. Not sure what is wrong.

**Comment by rgommers** [comment]
Ah, understood Matti's issue. Apparently permissions changed, this now requires full admin permission:
```
Merge pull requests on protected branches, even if there are no approving reviews
```
@mattip next time if you approve first, you should be able to merge I believe.

**Comment by rgommers** [comment]
I enabled branch protection on the `numpy.github.com` repo, requiring linear history, and upgraded @joelachance's permissions from "write" to "maintainer" - I think that should fix it.

**Comment by rgommers** [comment]
Same thing again, didn't fix the push permissions. I'll try a bit more.

**Comment by rgommers** [comment]
Okay I changed to token to one I generated, and that fixed it.

**Pull request merged**
