### PR TITLE
DOC: Add ImportError link for Install page

### PR DESCRIPTION
**Pull request by bjnath**
Give the Install page a pointer to the [Troubleshooting ImportError page](https://numpy.org/doc/stable/user/troubleshooting-importerror.html) in the Sphinx docs.

### CODE REVIEW

**Review by melissawm — APPROVED** [review]
LGTM, thanks @bjnath !

**Comment by bjnath** [comment]
Are we ready to merge this?

**Comment by rgommers** [comment]
Adding this link seems like a good idea to me, thanks @bjnath. I'm away from my dev setup right now, but I'll try to get back to this tomorrow and deploy this change to the website.

**Review by rgommers — APPROVED** [review]
LGTM, merging. Thanks @bjnath

**Pull request merged**
