### PR TITLE
Update theme

### PR DESCRIPTION
**Pull request by jarrodmillman**
Moving more stuff back from theme.  Everything should be the same except for the news.

### CODE REVIEW

**Comment by stefanv** [comment]
Current news:



New news (title followed by date instead of phrase):

**Comment by melissawm** [comment]
I am ok with this, maybe @InessaPawson and @MarsBarLee should also take a look.

**Review by melissawm — APPROVED** [review]

**Comment by InessaPawson** [comment]
I’d rather leave dates out. We don’t share news often, but the ones that make it on the news page are of great importance. By placing dates in the news bar we will be drawing attention to the information that is pretty trivial for the most stakeholders.

**Comment by stefanv** [comment]
I must say, to my eye the current version reads quite oddly. A date associated with a news item feels very natural! If you look at the SciPy news releases, e.g., they all start with a date.

Let's see what the others say too.

**Comment by InessaPawson** [comment]
To support my preference, see https://kotlinlang.org. 🤓

**Comment by stefanv** [comment]
I don't follow: their site does not seem to have a news/announcement section?

**Comment by InessaPawson** [comment]
@stefanv It's at the very top of the page (see the screenshot below).

Kotlin_newsbar

**Comment by stefanv** [comment]
Interesting, I don't see that banner in my browser!

**Comment by stefanv** [comment]
FWIW, I think it's OK to have a news announcement without any side-text.  But if there is side-text, a date seems appropriate.  The date can be suppressed in our current theme by simply not adding a date to the news site (it may be that I have to tweak that to work, but that'd be easy enough).

**Comment by InessaPawson** [comment]
No side-text would be fine. (I frankly don’t remember why we have it.) Thank you for being flexible!
P.S. The current announcement in the news bar could benefit from some tweaking.

**Comment by jarrodmillman** [comment]
@InessaPawson Sorry for the delay.  We've updated the theme to remove the side-text (if the date is not specified).  See 194e5d8ec5aa.  Now the news banner looks like this:
screenshot

**Review by InessaPawson — APPROVED** [review]
This looks great! Thank you, @jarrodmillman and @stefanv!

**Review by rgommers — APPROVED** [review]
LGTM too, thanks @jarrodmillman, all!

**Pull request merged**
