### PR TITLE
Use JupyterLite to try `numpy` in the browser

### LINKED ISSUE #466: Problems with the interactive terminal on the main page
The interactive terminal on the main page has never really worked that well for me. Specifically:
 - It can take a long time for the terminal instance to instantiate once the "enable" button has been clicked. I typically experience load times ~10 sec, but I've also experienced times in the 30s-1min range.
 - Once the terminal is live, it opens (for me) with a blank line and there is no indication (e.g. a flashing cursor) that it is ready for input
 - Acquiring the focus of the terminal is difficult - I would expect that clicking anywhere in the terminal box would enable typing in it, but IME it only works if you click on the first "row" in the terminal box. In addition - the first time you click on the first "row", it auto-populates with `import numpy as np`. Having this be the first line makes sense, but it's strange that it doesn't show up until you acquire the focus of the terminal
 - There is no history/output in the terminal, and no other indication that a command has been run. The terminal only displays output for a single command, and for commands that don't result in any ouput, there's no other indication that it ran at all. For example, if you run the first `import numpy as np` command, it remains on the input line and there is no output. In order to enter a new command, you have to manually delete the first line once it's been run. Similarly, any command that doesn't have output (e.g. `a = np.arange(10)`) has the same pattern: the command remains on the input line until it's manually deleted, and there is no indication that the command actually ran.

I realize that a lot of this may be browser-specific (I'm on Firefox) or related to the external services (e.g. Binder), but I thought it'd be worth reporting here.

### PR DESCRIPTION
**Pull request by jtpio**
#### Brief description of what is fixed or changed

This PR switches to using JupyterLite for the [numpy.org](https://numpy.org/) browser based demo.  Closes  #466.

This is what it looks like in action:

https://user-images.githubusercontent.com/591645/151985171-f9ad9c60-2cbd-407b-9733-545d2fa15b8d.mp4

JupyterLite is a JupyterLab distribution that runs entirely in the web browser, backed by in-browser language kernels including the WebAssembly powered [Pyodide](https://pyodide.org) kernel.

The embeddable code console is currently deployed as a static website on Vercel, and the source code is currently living in the following repository (this might change as we are still iterating on this): https://github.com/jtpio/replite

It also supports plotting matplotlib figures, for example:

image

There is also support for inline documentation (<kbd>Shift Tab</kbd>), as well as the `?` help, so it's more convenient to get the documentation for `numpy` functions:

image

image

**TODO**

- [x] Embed an interactive code console
- [x] Select the Pyodide based Python kernel by default (tracked in https://github.com/jtpio/replite/issues/1)
- [x] ~Move https://github.com/jtpio/replite to the `jupyterlite` organization on GitHub: https://github.com/jupyterlite~ -> this can be postponed to later since this will not affect the URL to the embeddable console

cc @stefanv @SylvainCorlay

### CODE REVIEW

**Comment by jtpio** [comment]
Looking good on the Netlify preview:

image

**Comment by joelachance** [comment]
This looks really nice @jtpio!

**Comment by rossbar** [comment]
This is great, I'd be in favor of getting this in sooner rather than later and handling improvements as follow-up PRs. Having something that works is the most important thing IMO!

**Comment by jtpio** [comment]
Thanks!

> This is great, I'd be in favor of getting this in sooner rather than later and handling improvements as follow-up PRs. Having something that works is the most important thing IMO!

Sounds good. Planning to do one more iteration tomorrow to bring it to a mergeable state.

**Comment by stefanv** [comment]
This is great, thanks @jtpio!  From what I can see it does not seem to impact load times either, so I presume it lazily loads whatever it needs?

Currently, when the shell is enabled example code is shown on the side; it would be good to retain that so users have something to type.

A nice-to-have would be to have `import numpy as np` executed automatically, so that the user can just start typing.

Another nice-to-have would be to have the terminal use witchhazel, or another slightly darker theme, but that can be added later.

**Comment by stefanv** [comment]
I've also noticed that, after loading the page if I type `import numpy as np`, it sometimes just sits there for a while; it may be confusing to the user not knowing whether something is happening in the background.  Maybe we (numpy web team) should add a text message around response time expectations.

**Comment by stefanv** [comment]
Oh, and tab completion ;)

**Comment by jtpio** [comment]
> From what I can see it does not seem to impact load times either, so I presume it lazily loads whatever it needs?

> I've also noticed that, after loading the page if I type import numpy as np, it sometimes just sits there for a while;

Right. The heaviest part for now is the kernel initialization. Now that it's possible to specify a kernel preference via a query string parameter (`?kernel=python`, enabled in this PR), it should help initialize the kernel in the background while the user scrolls down to the try section on the page.

> A nice-to-have would be to have import numpy as np executed automatically, so that the user can just start typing.

It's now possible to specify startup code as a query string parameter so the prompt cell is populated like this:

https://user-images.githubusercontent.com/591645/152127780-7f0686c8-15f6-4d3b-bf2f-fb414d0aa86f.mp4

For now it just populates the console prompt but we could indeed go one step further and execute it directly.

> Another nice-to-have would be to have the terminal use witchhazel, or another slightly darker theme, but that can be added later.

Actually since this is based on the JupyterLab stack, it already supports switching to other themes (after opening the command palette with <kbd>Ctrl Shift C</kbd>, for example the built-in JupyterLab dark theme:

https://user-images.githubusercontent.com/591645/152131127-625f07ab-22dd-4a71-b610-6c9b6eba687f.mp4

Otherwise maybe other themes could also be preinstalled and specified as a query string parameter.

> Oh, and tab completion ;)

This has been fixed upstream in JupyterLab (https://github.com/jupyterlab/jupyterlab/pull/11949) and should be released soon!

**Comment by jtpio** [comment]
The examples are back:

image

Marking as ready for review. Happy to make follow-up tweaks if needed.

**Comment by seberg** [comment]
This is awesome, and I think we should probably just put it in!  Two thoughts I had while looking at it:
* Maybe we should note that `shift + enter` runs the command somewhere?  Or can we just make it be enter?  The shell is _awesome_, but it feels potentially a bit too much for someone who has not used Python before really.
* Could we pre-import NumPy (could be hidden), so that `import numpy as np` is snappy?  Or `import numpy as np` could already be executed?

**Review by jarrodmillman — APPROVED** [review]

**Comment by jarrodmillman** [comment]
LGTM.  I am in favor or merging and iterating.  There are a few things I would like to change/improve, but this is already a vast improvement.

**Comment by jtpio** [comment]
> Maybe we should note that shift + enter runs the command somewhere? Or can we just make it be enter? The shell is awesome, but it feels potentially a bit too much for someone who has not used Python before really.

Maybe something like "Press Shift-Enter to run code" below the "Try Numpy"?

> Could we pre-import NumPy (could be hidden), so that import numpy as np is snappy? Or import numpy as np could already be executed?

Right, the `?code=` parameter could indeed execute the code directly.

Otherwise there is also a bunch of dead code and CSS related to the previous setup that could be cleaned up now.

**Review by rossbar — APPROVED** [review]
Agreed on getting this in and improving in follow up PRs. Thanks @jtpio this is really nice!

**Comment by jtpio** [comment]
> Maybe we should note that shift + enter runs the command somewhere? Or can we just make it be enter? The shell is awesome, but it feels potentially a bit too much for someone who has not used Python before really.

As an alternative to <kbd>Shift Enter</kbd>, it's also possible to drag and drop code in the prompt cell, and click on the "Run" button:

https://user-images.githubusercontent.com/591645/152300145-10ab5cc2-3e5f-437a-88b0-5cee057397bf.mp4

**Comment by stefanv** [comment]
One issue I noticed: page scrolls down to terminal after loading.

**Comment by stefanv** [comment]
Tab completion still isn't working for me after reload; perhaps that is dependent on a new upstream release.

I also notice a lot of errors in the console; it would be nice to sort those out.

@jtpio I like your suggestion from earlier:

> Maybe something like "Press Shift-Enter to run code" below the "Try Numpy"?

And removing the dead code is a bonus, but we can also take care of that.

Thanks again!

**Comment by jtpio** [comment]
> Tab completion still isn't working for me after reload; perhaps that is dependent on a new upstream release.

Yes it's still dependent on a new release JupyterLab, which is currently being worked on and should go out in the next coming days hopefully.

> I also notice a lot of errors in the console; it would be nice to sort those out.

Most of the dev tools errors should now be gone. The remaining `Uncaught TypeError: $(...).fadeOut is not a function` could be addressed in the follow-up PR that would clean up the unused code and CSS.

**Comment by stefanv** [comment]
I think the only blocker here is the focus issue.

**Comment by stefanv** [comment]
Our default example is a bit silly, since it does not print output!  Should probably add to

```python
samples = rng.normal(size=2500)
```

```
samples
```

or

```
print(samples
```

**Comment by SylvainCorlay** [comment]
> I think the only blocker here is the focus issue, and some text telling the user to press Shift-Enter to execute.

I don't understand what the focus issue is though.

**Comment by jtpio** [comment]
2 fixes:

- Added a quick comment at the top of the examples to mention the Shift Enter keyboard shortcut
- Basic code completion is back

image

**Comment by jtpio** [comment]
> > I think the only blocker here is the focus issue, and some text telling the user to press Shift-Enter to execute.
> 
> I don't understand what the focus issue is though.

This is the focus issue:

https://user-images.githubusercontent.com/591645/152544596-86e990c0-44b8-4431-8ee1-6b2840595b51.mp4

The page automatically scrolls to the code console when it loads. I am guessing one of the components grabs the focus. Need to investigate this a bit more to find a fix.

**Comment by stefanv** [comment]
@jtpio numpy.org may get quite a lot of visitors; I presume the CDN will be ok serving all the data? If it's a problem we can go back to a manual console.

**Comment by jtpio** [comment]
> quite a lot of visitors

Why kind of numbers are we talking about?

> I presume the CDN will be ok serving all the data?

For now the REPL is deployed to Vercel for the sake of simplicity, which is backed by a CDN. But if we notice scaling issues then we can consider deploying it to GitHub Pages or something similar, which should be just fine since some bigger websites with a high traffic are hosted there. It's a static website so we can easily move it around if needed.

**Comment by rgommers** [comment]
It's a couple of million visitors/month. However only a small percentage will be trying the REPL

**Comment by jtpio** [comment]
https://github.com/numpy/numpy.org/pull/547/commits/24386ff7ce6893c455405b5266e855bcc12c260e adds back the "Enable" button.

This should fix the scrolling issue since the console is now shown on user action after clicking on the "Enable" button:

https://user-images.githubusercontent.com/591645/152777269-12f7d537-e391-46c5-9977-08b14a84390d.mp4

The console is still loaded in the background so it pre-fetches the assets and can be ready when the user enables it.

**Review by stefanv — APPROVED** [review]

**Review by SylvainCorlay — APPROVED** [review]

**Comment by stefanv** [comment]
Thanks very much for this, @jtpio!

**Comment by jtpio** [comment]
Thanks all!

**Pull request merged**
