### PR TITLE
Fixes #92 Content added for Scientific domain tab via branch Issu92_sc_dom

### LINKED ISSUE #92: #Content: Scientific Domains Tab
Add content related to Scientific Domains in NumPy landing 'ecosystem' .

### PR DESCRIPTION
**Pull request by shaloo**
#### Deployed URL

https://pr-<pr_number>-numpy.surge.sh

### CODE REVIEW

**Comment by rgommers** [comment]
There's still something wrong in your setup @shaloo. We want the last commit here, not 175 commits. I'll review that commit and merge if it looks good.

After that you want to do:
```
git fetch upstream
git checkout master
git reset --hard upstream/master
```
And then create new branches only based off of master. You can delete your local `newsite` branch.

**Comment by rgommers** [comment]
The image is interesting, I like the concept:

image

There's a couple of issues with the image:
- Links aren't links because they're in a PNG, so they are a little deceiving. 
- The text in the image is tricky, because it won't be translated.
- The vertical lines in the two rows are spaced a bit irregularly.

Would it be possible to shrink the images in the bottom row a little, so the pattern comes out as:
```
|     |     |     |     |     |     |
   |     |     |     |     |     |
```
And then make it an SVG image so that text can be translated? If it's easy to keep the links in SVG, let's do that. Otherwise they could be removed from the image, and we can add some to the text in the paragraph above.

**Comment by rgommers** [comment]
@shaloo I've pushed a fix to your branch. You can update your local branch with:
```
git fetch origin
git checkout issu92_sc_dom
git reset --hard origin/issu92_sc_dom
```

**Comment by shaloo** [comment]
> There's still something wrong in your setup @shaloo. We want the last commit here, not 175 commits. I'll review that commit and merge if it looks good.
> 
> After that you want to do:
> 
> ```
> git fetch upstream
> git checkout master
> git reset --hard upstream/master
> ```
> 
> And then create new branches only based off of master. You can delete your local `newsite` branch.

Oh!  I did delete newsite a while back.  Will try these suggested reset/hard options and add the review edits accordingly.

**Comment by shaloo** [comment]
Where did the 39c7819 commit come from? It is again showing those 179 commits. Phew? It can't come via Hard reset? What am I missing?  Ah, I need to get this thing cleanup up and working so that I checkout latest master which is in sync totally with NumPy/master and then branch out of my synced up local master.

**Comment by rgommers** [comment]
> Where did the [39c7819](https://github.com/numpy/numpy.org/commit/39c78198d7f3680f6941ad5f9133a9fd10bda8c7) commit come from? It is again showing those 179 commits. Phew?

You must have done a `git merge` or `git pull` that created the merge commit `39c7819`. I'll clean it up again and let's try once more then with a set of instructions that do not include any `merge` or `pull`.

**Comment by rgommers** [comment]
Please try this:
```
git fetch upstream
git fetch origin
git checkout master
git branch --set-upstream-to upstream master
git reset --hard upstream/master
git checkout issu92_sc_dom
git reset --hard origin/issu92_sc_dom
```
You should see no merge commits anywhere, and when you look at things with, e.g., `gitk --all` you should see that your local `master` is in sync with upstream master, and your `issu92_sc_dom` is one commit ahead and in sync with `origin/issu92_sc_dom`.

**Comment by shaloo** [comment]
Done, looks like i have a clean slate now.  Just to validate, I made a single line change (removed the image ) and committed to shaloo/numpy.org branch issu92_sc_dom.  When I compare it with NumPy.org/master -  I see at least three files changed in GitHub UI (compare screen).  But not 170+ changes. Updating PR with single line change to see how this goes...

**Comment by shaloo** [comment]
Alright, I see only 1 line change as expected so all looks good now. Thanks.  Will incorporate the suggested PR changes now and commit shortly.

**Comment by shaloo** [comment]
@rgommers: If this visualisation and content for "Scientific Domain" tab looks better, pls merge in NumPy.org master branch. thx.

**Comment by rgommers** [comment]
> This is how the updates look like using Safari browser. I've used responsive UI elements.

Oo, this looks quite nice:) I'll merge this now, the image looks great. We may want to replace a couple of the older project names with newer ones, but that can be done easily now that links are separate from the image itself.

Sorry for the delay in reviewing. In it goes!

**Pull request merged**
