### PR TITLE
Travis re-setup - removed the docker 

### PR DESCRIPTION
**Pull request by Shekharrajak**
#### Brief description of what is fixed or changed

Continuation of https://github.com/numpy/numpy.org/pull/146

As per the discussion: https://github.com/numpy/numpy.org/pull/146#issuecomment-581064436

#### Deployed URL

http://numpy-166.surge.sh/

### CODE REVIEW

**Comment by Shekharrajak** [comment]
Getting an error: https://github.com/sintaxi/surge/issues/395

**Comment by rgommers** [comment]
This is all green, but there's still a problem on the Surge site. @Shekharrajak I'm happy to merge this now and you can continue in a second PR, or you can iterate on this one - whatever you prefer.

**Comment by Shekharrajak** [comment]
Yes, sure! We can merge it for now.

**Comment by rgommers** [comment]
Merged, thanks Shekhar

**Pull request merged**
