### PR TITLE
Add network/graph category

### PR DESCRIPTION
**Pull request by jarrodmillman**
Fixes gh-320.  See https://github.com/numpy/numpy.org/issues/313#issuecomment-751466980.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks Jarrod. Having another look around for other packages that may deserve a mention, what do you think about these:
- https://igraph.org/python/
- https://snap.stanford.edu/snappy/
- https://scikit-network.readthedocs.io/en/latest/

They all seem solid/popular/maintained, and it's not clear to me how they compare against graph-tool and PyGSP.

**Comment by mdeff** [comment]
NetworkX, graph-tool, igraph, [NetworKit](https://networkit.github.io), snappy, scikit-network do [network science](https://en.wikipedia.org/wiki/Network_science): they are concerned with the analysis of networks. PyGSP, which stands for Graph Signal Processing, is more concerned with the analysis of data / features / signals supported by networks (as functions of vertices) and is closer to ([spectral](https://en.wikipedia.org/wiki/Spectral_graph_theory)) [graph theory](https://en.wikipedia.org/wiki/Graph_theory).

I have the following to say about the NetSci category:
* NetworkX is definitely the most popular
* graph-tool is well polished and maintained by its author, more mature and probably a bit more popular than NetworKit
* scikit-network is too new (first commit a year ago)
* snap and their Python SWIG interface (snappy) seems mostly used internally (by Leskovec's group at Stanford)
* igraph and NetworKit are both solid complements to NetworkX and graph-tool
* igraph is however more popular (e.g., 257,455 vs 29,153 downloads from conda-forge, or dependent projects on github and libraries.io) and mature (first commit 14 vs 7 years ago).

I see two alternative categories depending on whether or not you want to take the alternative PyGSP point-of-view:
1. Network Science: NetworkX, graph-tool, igraph, NetworKit
2. Graphs and Networks: NetworkX, graph-tool, igraph, PyGSP

I'd vote for 2, but as the author of PyGSP I'm of course biased.

**Comment by rgommers** [comment]
Thanks for the thorough overview @mdeff 

> I'd vote for 2, but as the author of PyGSP I'm of course biased.

I'm happy to go with this option. "Graphs and Networks" does sound better to me.

**Comment by jarrodmillman** [comment]
I updated the PR to go with option 2.

I also slightly changed the icon.  I committed the script that generates it:
- static/images/content_images/sc_dom_img/graph.py 

Feel free to change the colors, line thickess, or whatever.  Or let me know if you want me to change something.

Is there a better place to put the script?  Should I take it out of the repo?

**Comment by jarrodmillman** [comment]
I just looked #369 and noticed it looks like they got rid of the colors and the grays.  I'll change the icon again.

**Comment by rgommers** [comment]
Adding the script next to the icon sounds fine to me. Would it be possible to make the png size smaller though @jarrodmillman? The new icon is 10x larger than the other icons, 250 kb is a lot for a small image.

**Comment by mdeff** [comment]
Why not export as SVG? Should be small given the small number of elements. I think they're moving to SVG in gh-369.

**Comment by jarrodmillman** [comment]
I saved the icon as a SVG instead of a PNG.  It is now 8.0K.

I also made it 160px by 120px.  I couldn't find any specification of the preferred size, so I just randomly selected one of the existing PNGs and used its width.

**Review by rgommers — APPROVED** [review]
LGTM now, thanks @jarrodmillman!

**Pull request merged**
