### PR TITLE
travis setup config file added

### PR DESCRIPTION
**Pull request by Shekharrajak**
* Travis config file added 
* Removed the github actions and workflow since now we are using travis for the same.

#### Deployed URL

http://numpy-124.surge.sh/

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @Shekharrajak. I just installed the TravisCI app for this repo as you asked

**Comment by Shekharrajak** [comment]
> Thanks @Shekharrajak. I just installed the TravisCI app for this repo as you asked

Thanks! I am testing it.

**Comment by Shekharrajak** [comment]
It is working fine for travis. We can merge it once reviewed.

**Comment by rgommers** [comment]
@Shekharrajak the deployed site is there, but I'm not sure I understand what is going on. We have three successful CI actions:

image

I had expected only one, on TravisCI. Can you explain what each part is doing?

**Comment by Shekharrajak** [comment]
> @Shekharrajak the deployed site is there, but I'm not sure I understand what is going on. We have three successful CI actions:
> 
> image
> 
> I had expected only one, on TravisCI. Can you explain what each part is doing?

I didn't remove the GitHub workflow logic yet. Maybe we can continue with the same later or can expand the workflow to do something else (Should I remove it completely ?)

Travis have 2 options - Workflow 1 for the "branch push" and  2nd for "PR  default branch (master)".
So if we commit to the specific branch then we can write the corresponding workflow.

Let me know if you want only PR CI/CD to run as of now. We can do the change in travis repo setting.

**Comment by rgommers** [comment]
Ah okay. Yes, let's remove GitHub Actions, and trigger only on PRs. Deploying merge commits or direct pushes to Surge doesn't seem useful.

**Comment by Shekharrajak** [comment]
> Ah okay. Yes, let's remove GitHub Actions, and trigger only on PRs. Deploying merge commits or direct pushes to Surge doesn't seem useful.

Github actions and workflow is removed and now Travis PR and push CI will trigger.

**Comment by rgommers** [comment]
This still shows 3 checks, but maybe the setup is confused because of the history of this PR. Let's merge this and continue in a new PR if needed. Thanks @Shekharrajak

**Pull request merged**
