### PR TITLE
Resolved issue #443: UnicodeEncodeError

### PR DESCRIPTION
**Pull request by Uttam-Singhh**
Described everything in  #443. 
 
You can refer to this link for more info: https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters

P.S -  I have used `io` because **it gives you backward compatibility with Python 2 as well.**

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
Thanks @Uttam-Singhh! The fix looks good to me.

Can you undo the `io` change? Python 2 is well past end-of-life, and we don't want to carry around code to support it.

**Comment by Uttam-Singhh** [comment]
Done @rgommer!
Please check...

**Review by rgommers — APPROVED** [review]
Thanks @Uttam-Singhh

**Comment by Uttam-Singhh** [comment]
Thank you @rgommers!

**Pull request merged**
