### PR TITLE
make it clear this is a news item on the news page

### PR DESCRIPTION
**Pull request by mattip**
Add a "News:" title, use double-quotes to make hugo happy

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @mattip. I'm happy with either the old or the new here. @InessaPawson and @joelachance, are you fine with making this change?

_old version_:

image


_version with this PR_:

image

**Comment by InessaPawson** [comment]
I prefer the old version.

**Comment by joelachance** [comment]
Just saw this-- I think I prefer the old version as well.

**Comment by mattip** [comment]
OK, closing.

**Pull request closed without merging**
