### PR TITLE
add link back to main page (instead of scipy.org)

### PR DESCRIPTION
**Pull request by mattip**
Continuation of #25

### CODE REVIEW

**Comment by mattip** [comment]
Once this is merged we should rebuild the site so this and #25 take effect

**Comment by rgommers** [comment]
Thanks!

> Once this is merged we should rebuild the site so this and #25 take effect

wasn't this auto-building now?

**Comment by mattip** [comment]
There is no CI at all in this repo

**Comment by rgommers** [comment]
oh okay, then I'm confusing things - sorry for the noise

**Pull request merged**
