### PR TITLE
Update theme (0.5)

### PR DESCRIPTION
**Pull request by jarrodmillman**
**We should do this as a merge commit (not squash and merge).**

This is a major theme update to align us more with the styling and accessibility work being done on pydata-sphinx-theme.

Currently the dark theme mode is disabled. We will make a follow-up PR to enable the dark theme mode as it will involve updates to several images.

See the release notes for more details:
- https://github.com/scientific-python/scientific-python-hugo-theme/releases/tag/v0.2
- https://github.com/scientific-python/scientific-python-hugo-theme/releases/tag/v0.3
- https://github.com/scientific-python/scientific-python-hugo-theme/releases/tag/v0.4
- https://github.com/scientific-python/scientific-python-hugo-theme/releases/tag/v0.5

### CODE REVIEW

**Comment by stefanv** [comment]
- About: Missing OpenCollective widget
- Case studies: block quotes rendering incorrectly
- Tabs: last two tabs seem to have rendering problems; also check dark mode
- Footer: sign up for mailing list box misaligned
- Language drop down: wrong color in dark mode (should be fixed in theme?)
- Copyright owner missing; add `name` to `author` field in `config.yaml`
- [Optional] Logos not rendering well in dark mode (scientific domains; sponsorships on About)

**Comment by alphapapa** [comment]
@jarrodmillman @stefanv While working on updating the "Ecosystem/Scientific Domains" tab (to use CSS flex and simplify the configuration, which was half in an HTML template and half in a YAML file), I pushed https://github.com/scientific-python/scientific-python-hugo-theme/pull/413, which will allow the use of Sass files in downstream sites.  That makes the CSS related to these tabs much simpler and more concise.

**Comment by alphapapa** [comment]
Since I'm unable to push to this PR's branch, I'm pushing to my fork here: https://github.com/alphapapa/numpy.org/commits/theme-0.5

**Comment by stefanv** [comment]
@jarrodmillman Shall we pin the latest commit on the theme and set this ready for review?

**Comment by jarrodmillman** [comment]
I am going to make a 0.5 release first.

**Review by InessaPawson — APPROVED** [review]
@jarrodmillman This is quite a change! Let's give it a go.

**Comment by alphapapa** [comment]
> ## Future PR
> * [ ]  dark theme
>   
>   * [ ]  Undo [dae065e](https://github.com/numpy/numpy.org/commit/dae065e6da644a1296d900dc5daa1fc7496ece7b)
>   * [ ]  Logos not rendering well in dark mode (scientific domains; sponsorships on About)
>   * [ ]  Tabs: last two tabs seem to have rendering problems; also check dark mode
>     `color`
>   * [ ]  Language drop down: wrong color in dark mode (should be fixed in theme?)

For future reference, see https://github.com/numpy/numpy.org/issues/707 for these issues.

**Pull request merged**
